# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response200100_settings_question_and_answer import InlineResponse200100SettingsQuestionAndAnswer  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse200100SettingsQuestionAndAnswer(unittest.TestCase):
    """InlineResponse200100SettingsQuestionAndAnswer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200100SettingsQuestionAndAnswer(self):
        """Test InlineResponse200100SettingsQuestionAndAnswer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response200100_settings_question_and_answer.InlineResponse200100SettingsQuestionAndAnswer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
