# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20093_meeting_security import InlineResponse20093MeetingSecurity  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20093MeetingSecurity(unittest.TestCase):
    """InlineResponse20093MeetingSecurity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20093MeetingSecurity(self):
        """Test InlineResponse20093MeetingSecurity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20093_meeting_security.InlineResponse20093MeetingSecurity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
