# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_id3 import UserId3  # noqa: E501
from swagger_client.rest import ApiException


class TestUserId3(unittest.TestCase):
    """UserId3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserId3(self):
        """Test UserId3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_id3.UserId3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
