# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20088_phone_numbers import InlineResponse20088PhoneNumbers  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20088PhoneNumbers(unittest.TestCase):
    """InlineResponse20088PhoneNumbers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20088PhoneNumbers(self):
        """Test InlineResponse20088PhoneNumbers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20088_phone_numbers.InlineResponse20088PhoneNumbers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
