# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zoom
from zoom.models.accountsaccount_idsettings_in_meeting_auto_generated_translation_language_item_pair_list_speak_language import AccountsaccountIdsettingsInMeetingAutoGeneratedTranslationLanguageItemPairListSpeakLanguage  # noqa: E501
from zoom.rest import ApiException


class TestAccountsaccountIdsettingsInMeetingAutoGeneratedTranslationLanguageItemPairListSpeakLanguage(unittest.TestCase):
    """AccountsaccountIdsettingsInMeetingAutoGeneratedTranslationLanguageItemPairListSpeakLanguage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountsaccountIdsettingsInMeetingAutoGeneratedTranslationLanguageItemPairListSpeakLanguage(self):
        """Test AccountsaccountIdsettingsInMeetingAutoGeneratedTranslationLanguageItemPairListSpeakLanguage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zoom.models.accountsaccount_idsettings_in_meeting_auto_generated_translation_language_item_pair_list_speak_language.AccountsaccountIdsettingsInMeetingAutoGeneratedTranslationLanguageItemPairListSpeakLanguage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
