# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20039_meeting_security import InlineResponse20039MeetingSecurity  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20039MeetingSecurity(unittest.TestCase):
    """InlineResponse20039MeetingSecurity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20039MeetingSecurity(self):
        """Test InlineResponse20039MeetingSecurity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20039_meeting_security.InlineResponse20039MeetingSecurity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
