# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zoom
from zoom.models.inline_response2002_schedule_meeting_meeting_password_requirement import InlineResponse2002ScheduleMeetingMeetingPasswordRequirement  # noqa: E501
from zoom.rest import ApiException


class TestInlineResponse2002ScheduleMeetingMeetingPasswordRequirement(unittest.TestCase):
    """InlineResponse2002ScheduleMeetingMeetingPasswordRequirement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002ScheduleMeetingMeetingPasswordRequirement(self):
        """Test InlineResponse2002ScheduleMeetingMeetingPasswordRequirement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zoom.models.inline_response2002_schedule_meeting_meeting_password_requirement.InlineResponse2002ScheduleMeetingMeetingPasswordRequirement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
