# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20059_dedicated_dial_in_number import InlineResponse20059DedicatedDialInNumber  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20059DedicatedDialInNumber(unittest.TestCase):
    """InlineResponse20059DedicatedDialInNumber unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20059DedicatedDialInNumber(self):
        """Test InlineResponse20059DedicatedDialInNumber"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20059_dedicated_dial_in_number.InlineResponse20059DedicatedDialInNumber()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
