# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zoom
from zoom.models.inline_response2002_schedule_meeting_meeting_template_templates import InlineResponse2002ScheduleMeetingMeetingTemplateTemplates  # noqa: E501
from zoom.rest import ApiException


class TestInlineResponse2002ScheduleMeetingMeetingTemplateTemplates(unittest.TestCase):
    """InlineResponse2002ScheduleMeetingMeetingTemplateTemplates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002ScheduleMeetingMeetingTemplateTemplates(self):
        """Test InlineResponse2002ScheduleMeetingMeetingTemplateTemplates"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zoom.models.inline_response2002_schedule_meeting_meeting_template_templates.InlineResponse2002ScheduleMeetingMeetingTemplateTemplates()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
