# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zoom
from zoom.models.tracking_field2 import TrackingField2  # noqa: E501
from zoom.rest import ApiException


class TestTrackingField2(unittest.TestCase):
    """TrackingField2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrackingField2(self):
        """Test TrackingField2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zoom.models.tracking_field2.TrackingField2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
