# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zoom
from zoom.models.inline_response20093_authentication_options_recording_authentication_authentication_options import InlineResponse20093AuthenticationOptionsRecordingAuthenticationAuthenticationOptions  # noqa: E501
from zoom.rest import ApiException


class TestInlineResponse20093AuthenticationOptionsRecordingAuthenticationAuthenticationOptions(unittest.TestCase):
    """InlineResponse20093AuthenticationOptionsRecordingAuthenticationAuthenticationOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20093AuthenticationOptionsRecordingAuthenticationAuthenticationOptions(self):
        """Test InlineResponse20093AuthenticationOptionsRecordingAuthenticationAuthenticationOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zoom.models.inline_response20093_authentication_options_recording_authentication_authentication_options.InlineResponse20093AuthenticationOptionsRecordingAuthenticationAuthenticationOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
