# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zoom
from zoom.models.registration_list_registrants import RegistrationListRegistrants  # noqa: E501
from zoom.rest import ApiException


class TestRegistrationListRegistrants(unittest.TestCase):
    """RegistrationListRegistrants unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistrationListRegistrants(self):
        """Test RegistrationListRegistrants"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zoom.models.registration_list_registrants.RegistrationListRegistrants()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
