# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tsp_accounts_list1 import TSPAccountsList1  # noqa: E501
from swagger_client.rest import ApiException


class TestTSPAccountsList1(unittest.TestCase):
    """TSPAccountsList1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTSPAccountsList1(self):
        """Test TSPAccountsList1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tsp_accounts_list1.TSPAccountsList1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
