# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20069_operation_logs import InlineResponse20069OperationLogs  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20069OperationLogs(unittest.TestCase):
    """InlineResponse20069OperationLogs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20069OperationLogs(self):
        """Test InlineResponse20069OperationLogs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20069_operation_logs.InlineResponse20069OperationLogs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
