# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zoom
from zoom.models.user_settings_meeting_settings1_webinar_live_streaming import UserSettingsMeetingSettings1WebinarLiveStreaming  # noqa: E501
from zoom.rest import ApiException


class TestUserSettingsMeetingSettings1WebinarLiveStreaming(unittest.TestCase):
    """UserSettingsMeetingSettings1WebinarLiveStreaming unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserSettingsMeetingSettings1WebinarLiveStreaming(self):
        """Test UserSettingsMeetingSettings1WebinarLiveStreaming"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zoom.models.user_settings_meeting_settings1_webinar_live_streaming.UserSettingsMeetingSettings1WebinarLiveStreaming()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
