# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zoom
from zoom.api.contact_groups_api import ContactGroupsApi  # noqa: E501
from zoom.rest import ApiException


class TestContactGroupsApi(unittest.TestCase):
    """ContactGroupsApi unit test stubs"""

    def setUp(self):
        self.api = ContactGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contact_group(self):
        """Test case for contact_group

        Get a contact group  # noqa: E501
        """
        pass

    def test_contact_group_create(self):
        """Test case for contact_group_create

        Create a contact group  # noqa: E501
        """
        pass

    def test_contact_group_delete(self):
        """Test case for contact_group_delete

        Delete a contact group  # noqa: E501
        """
        pass

    def test_contact_group_member_add(self):
        """Test case for contact_group_member_add

        Add contact group members  # noqa: E501
        """
        pass

    def test_contact_group_member_remove(self):
        """Test case for contact_group_member_remove

        Remove members in a contact group  # noqa: E501
        """
        pass

    def test_contact_group_members(self):
        """Test case for contact_group_members

        List contact group members  # noqa: E501
        """
        pass

    def test_contact_group_update(self):
        """Test case for contact_group_update

        Update a contact group  # noqa: E501
        """
        pass

    def test_contact_groups(self):
        """Test case for contact_groups

        List contact groups  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
