# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zoom
from zoom.models.inline_response2002_in_meeting_auto_generated_translation_language_item_pair_list_translate_to import InlineResponse2002InMeetingAutoGeneratedTranslationLanguageItemPairListTranslateTo  # noqa: E501
from zoom.rest import ApiException


class TestInlineResponse2002InMeetingAutoGeneratedTranslationLanguageItemPairListTranslateTo(unittest.TestCase):
    """InlineResponse2002InMeetingAutoGeneratedTranslationLanguageItemPairListTranslateTo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002InMeetingAutoGeneratedTranslationLanguageItemPairListTranslateTo(self):
        """Test InlineResponse2002InMeetingAutoGeneratedTranslationLanguageItemPairListTranslateTo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zoom.models.inline_response2002_in_meeting_auto_generated_translation_language_item_pair_list_translate_to.InlineResponse2002InMeetingAutoGeneratedTranslationLanguageItemPairListTranslateTo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
