# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.participant_qos_audio_device_from_crc import ParticipantQOSAudioDeviceFromCrc  # noqa: E501
from swagger_client.rest import ApiException


class TestParticipantQOSAudioDeviceFromCrc(unittest.TestCase):
    """ParticipantQOSAudioDeviceFromCrc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParticipantQOSAudioDeviceFromCrc(self):
        """Test ParticipantQOSAudioDeviceFromCrc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.participant_qos_audio_device_from_crc.ParticipantQOSAudioDeviceFromCrc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
