# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zoom
from zoom.models.the_h323_sip_device_object_ import TheH323SIPDeviceObject_  # noqa: E501
from zoom.rest import ApiException


class TestTheH323SIPDeviceObject_(unittest.TestCase):
    """TheH323SIPDeviceObject_ unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTheH323SIPDeviceObject_(self):
        """Test TheH323SIPDeviceObject_"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zoom.models.the_h323_sip_device_object_.TheH323SIPDeviceObject_()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
