# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zoom
from zoom.models.inline_response20043 import InlineResponse20043  # noqa: E501
from zoom.rest import ApiException


class TestInlineResponse20043(unittest.TestCase):
    """InlineResponse20043 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20043(self):
        """Test InlineResponse20043"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zoom.models.inline_response20043.InlineResponse20043()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
