# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.participant_qos1_audio_device_from_crc import ParticipantQOS1AudioDeviceFromCrc  # noqa: E501
from swagger_client.rest import ApiException


class TestParticipantQOS1AudioDeviceFromCrc(unittest.TestCase):
    """ParticipantQOS1AudioDeviceFromCrc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParticipantQOS1AudioDeviceFromCrc(self):
        """Test ParticipantQOS1AudioDeviceFromCrc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.participant_qos1_audio_device_from_crc.ParticipantQOS1AudioDeviceFromCrc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
