# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import zoom
from zoom.models.inline_response2009_participant_audio_files import InlineResponse2009ParticipantAudioFiles  # noqa: E501
from zoom.rest import ApiException


class TestInlineResponse2009ParticipantAudioFiles(unittest.TestCase):
    """InlineResponse2009ParticipantAudioFiles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2009ParticipantAudioFiles(self):
        """Test InlineResponse2009ParticipantAudioFiles"""
        # FIXME: construct object with mandatory attributes with example values
        # model = zoom.models.inline_response2009_participant_audio_files.InlineResponse2009ParticipantAudioFiles()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
