# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GroupsgroupIdlockSettingsOtherOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'blur_snapshot': 'bool'
    }

    attribute_map = {
        'blur_snapshot': 'blur_snapshot'
    }

    def __init__(self, blur_snapshot=None):  # noqa: E501
        """GroupsgroupIdlockSettingsOtherOptions - a model defined in Swagger"""  # noqa: E501
        self._blur_snapshot = None
        self.discriminator = None
        if blur_snapshot is not None:
            self.blur_snapshot = blur_snapshot

    @property
    def blur_snapshot(self):
        """Gets the blur_snapshot of this GroupsgroupIdlockSettingsOtherOptions.  # noqa: E501

        If true, iOS blurs the screenshot in the task switcher when multiple apps are open. Android hides the screenshot in the system-level list of recent apps.  # noqa: E501

        :return: The blur_snapshot of this GroupsgroupIdlockSettingsOtherOptions.  # noqa: E501
        :rtype: bool
        """
        return self._blur_snapshot

    @blur_snapshot.setter
    def blur_snapshot(self, blur_snapshot):
        """Sets the blur_snapshot of this GroupsgroupIdlockSettingsOtherOptions.

        If true, iOS blurs the screenshot in the task switcher when multiple apps are open. Android hides the screenshot in the system-level list of recent apps.  # noqa: E501

        :param blur_snapshot: The blur_snapshot of this GroupsgroupIdlockSettingsOtherOptions.  # noqa: E501
        :type: bool
        """

        self._blur_snapshot = blur_snapshot

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupsgroupIdlockSettingsOtherOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupsgroupIdlockSettingsOtherOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
