# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2017(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'is_default': 'bool',
        'name': 'str',
        'size': 'int',
        'type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'is_default': 'is_default',
        'name': 'name',
        'size': 'size',
        'type': 'type'
    }

    def __init__(self, id=None, is_default=None, name=None, size=None, type=None):  # noqa: E501
        """InlineResponse2017 - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._is_default = None
        self._name = None
        self._size = None
        self._type = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if is_default is not None:
            self.is_default = is_default
        if name is not None:
            self.name = name
        if size is not None:
            self.size = size
        if type is not None:
            self.type = type

    @property
    def id(self):
        """Gets the id of this InlineResponse2017.  # noqa: E501

        The file's ID.  # noqa: E501

        :return: The id of this InlineResponse2017.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2017.

        The file's ID.  # noqa: E501

        :param id: The id of this InlineResponse2017.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def is_default(self):
        """Gets the is_default of this InlineResponse2017.  # noqa: E501

        Whether the file is the default Virtual Background file.  # noqa: E501

        :return: The is_default of this InlineResponse2017.  # noqa: E501
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default):
        """Sets the is_default of this InlineResponse2017.

        Whether the file is the default Virtual Background file.  # noqa: E501

        :param is_default: The is_default of this InlineResponse2017.  # noqa: E501
        :type: bool
        """

        self._is_default = is_default

    @property
    def name(self):
        """Gets the name of this InlineResponse2017.  # noqa: E501

        The file's name.  # noqa: E501

        :return: The name of this InlineResponse2017.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse2017.

        The file's name.  # noqa: E501

        :param name: The name of this InlineResponse2017.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def size(self):
        """Gets the size of this InlineResponse2017.  # noqa: E501

        The file's size, in bytes.  # noqa: E501

        :return: The size of this InlineResponse2017.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this InlineResponse2017.

        The file's size, in bytes.  # noqa: E501

        :param size: The size of this InlineResponse2017.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def type(self):
        """Gets the type of this InlineResponse2017.  # noqa: E501

        The file type.  # noqa: E501

        :return: The type of this InlineResponse2017.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InlineResponse2017.

        The file type.  # noqa: E501

        :param type: The type of this InlineResponse2017.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2017, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2017):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
