# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20078(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'id': 'str',
        'name': 'str',
        'type': 'str',
        'privileges': 'list[str]',
        'sub_account_privileges': 'InlineResponse20078SubAccountPrivileges',
        'total_members': 'int'
    }

    attribute_map = {
        'description': 'description',
        'id': 'id',
        'name': 'name',
        'type': 'type',
        'privileges': 'privileges',
        'sub_account_privileges': 'sub_account_privileges',
        'total_members': 'total_members'
    }

    def __init__(self, description=None, id=None, name=None, type=None, privileges=None, sub_account_privileges=None, total_members=None):  # noqa: E501
        """InlineResponse20078 - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._id = None
        self._name = None
        self._type = None
        self._privileges = None
        self._sub_account_privileges = None
        self._total_members = None
        self.discriminator = None
        if description is not None:
            self.description = description
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if privileges is not None:
            self.privileges = privileges
        if sub_account_privileges is not None:
            self.sub_account_privileges = sub_account_privileges
        if total_members is not None:
            self.total_members = total_members

    @property
    def description(self):
        """Gets the description of this InlineResponse20078.  # noqa: E501

        The role's description.  # noqa: E501

        :return: The description of this InlineResponse20078.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InlineResponse20078.

        The role's description.  # noqa: E501

        :param description: The description of this InlineResponse20078.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this InlineResponse20078.  # noqa: E501

        The role's  Id.  # noqa: E501

        :return: The id of this InlineResponse20078.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20078.

        The role's  Id.  # noqa: E501

        :param id: The id of this InlineResponse20078.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this InlineResponse20078.  # noqa: E501

        The role's name.  # noqa: E501

        :return: The name of this InlineResponse20078.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20078.

        The role's name.  # noqa: E501

        :param name: The name of this InlineResponse20078.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this InlineResponse20078.  # noqa: E501

        The role's type.  # noqa: E501

        :return: The type of this InlineResponse20078.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InlineResponse20078.

        The role's type.  # noqa: E501

        :param type: The type of this InlineResponse20078.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def privileges(self):
        """Gets the privileges of this InlineResponse20078.  # noqa: E501

        Privileges assigned to the role. Can be one or more of [these permissions](https://developers.zoom.us/docs/api/rest/other-references/privileges/).   # noqa: E501

        :return: The privileges of this InlineResponse20078.  # noqa: E501
        :rtype: list[str]
        """
        return self._privileges

    @privileges.setter
    def privileges(self, privileges):
        """Sets the privileges of this InlineResponse20078.

        Privileges assigned to the role. Can be one or more of [these permissions](https://developers.zoom.us/docs/api/rest/other-references/privileges/).   # noqa: E501

        :param privileges: The privileges of this InlineResponse20078.  # noqa: E501
        :type: list[str]
        """

        self._privileges = privileges

    @property
    def sub_account_privileges(self):
        """Gets the sub_account_privileges of this InlineResponse20078.  # noqa: E501


        :return: The sub_account_privileges of this InlineResponse20078.  # noqa: E501
        :rtype: InlineResponse20078SubAccountPrivileges
        """
        return self._sub_account_privileges

    @sub_account_privileges.setter
    def sub_account_privileges(self, sub_account_privileges):
        """Sets the sub_account_privileges of this InlineResponse20078.


        :param sub_account_privileges: The sub_account_privileges of this InlineResponse20078.  # noqa: E501
        :type: InlineResponse20078SubAccountPrivileges
        """

        self._sub_account_privileges = sub_account_privileges

    @property
    def total_members(self):
        """Gets the total_members of this InlineResponse20078.  # noqa: E501

        Total members assigned to that role.  # noqa: E501

        :return: The total_members of this InlineResponse20078.  # noqa: E501
        :rtype: int
        """
        return self._total_members

    @total_members.setter
    def total_members(self, total_members):
        """Sets the total_members of this InlineResponse20078.

        Total members assigned to that role.  # noqa: E501

        :param total_members: The total_members of this InlineResponse20078.  # noqa: E501
        :type: int
        """

        self._total_members = total_members

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20078, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20078):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
