# coding: utf-8

"""
    Zoom Meeting API

    The Zoom Meeting APIs let developers to access information from Zoom.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20059GlobalDialInNumbers(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'country': 'str',
        'number': 'str'
    }

    attribute_map = {
        'country': 'country',
        'number': 'number'
    }

    def __init__(self, country=None, number=None):  # noqa: E501
        """InlineResponse20059GlobalDialInNumbers - a model defined in Swagger"""  # noqa: E501
        self._country = None
        self._number = None
        self.discriminator = None
        if country is not None:
            self.country = country
        if number is not None:
            self.number = number

    @property
    def country(self):
        """Gets the country of this InlineResponse20059GlobalDialInNumbers.  # noqa: E501

        The global dial-in country code.  # noqa: E501

        :return: The country of this InlineResponse20059GlobalDialInNumbers.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this InlineResponse20059GlobalDialInNumbers.

        The global dial-in country code.  # noqa: E501

        :param country: The country of this InlineResponse20059GlobalDialInNumbers.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def number(self):
        """Gets the number of this InlineResponse20059GlobalDialInNumbers.  # noqa: E501

        The global dial-in number.  # noqa: E501

        :return: The number of this InlineResponse20059GlobalDialInNumbers.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this InlineResponse20059GlobalDialInNumbers.

        The global dial-in number.  # noqa: E501

        :param number: The number of this InlineResponse20059GlobalDialInNumbers.  # noqa: E501
        :type: str
        """

        self._number = number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20059GlobalDialInNumbers, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20059GlobalDialInNumbers):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
